// Extended TUI color theme for ocforge (dashboard mode)
export const THEME = {
  bg: '#1a1a2e',
  border: '#00bcd4',
  borderDim: '#0d7377',
  headerFg: '#00e5ff',
  panelHeader: '#4caf50',
  textPrimary: '#e0e0e0',
  textSecondary: '#9e9e9e',
  textMuted: '#616161',
  selectedBg: '#263238',
  selectedFg: '#ffffff',
  highlight: '#ff9800',
  success: '#4caf50',
  error: '#f44336',
  warning: '#ff9800',
  info: '#2196f3',
  agent: '#e91e63',
  category: '#9c27b0',
  model: '#00bcd4',
};

export const BORDER_STYLE = {
  single: {
    topLeft: '┌',
    topRight: '┐',
    bottomLeft: '└',
    bottomRight: '┘',
    horizontal: '─',
    vertical: '│',
    topJoin: '┬',
    bottomJoin: '┴',
    leftJoin: '├',
    rightJoin: '┤',
    cross: '┼',
  },
  double: {
    topLeft: '╔',
    topRight: '╗',
    bottomLeft: '╚',
    bottomRight: '╝',
    horizontal: '═',
    vertical: '║',
    topJoin: '╦',
    bottomJoin: '╩',
    leftJoin: '╠',
    rightJoin: '╣',
    cross: '╬',
  },
};
